# Generated by Django 2.2.10 on 2021-05-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='begining_date',
            new_name='beginning_date',
        ),
    ]
