# Generated by Django 2.2.10 on 2021-05-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answer_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='polls.Questionnaire', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='polls.Survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey', verbose_name='Опрос'),
        ),
    ]
