# Generated by Django 2.2.10 on 2021-05-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210516_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='polls.Survey', verbose_name='Опрос'),
        ),
    ]
