# Generated by Django 2.2.10 on 2021-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210516_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ'),
        ),
    ]
